version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    networks:
      - app-network
    volumes:
      - ./log.txt:/var/log/log.txt

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
